# Generated by Django 5.1.6 on 2025-02-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://pbs.twimg.com/media/GkBdSs2aAAI8rhT?format=jpg&name=small",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_desc",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
