# Generated by Django 5.1.6 on 2025-02-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodapp", "0002_item_item_image_alter_item_item_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                blank=True,
                default="https://pbs.twimg.com/media/GkBdSs2aAAI8rhT?format=jpg&name=small",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_price",
            field=models.FloatField(),
        ),
    ]
