# Generated by Django 5.1.6 on 2025-02-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                (
                    "profile",
                    models.CharField(
                        blank=True,
                        default="https://www.nicepng.com/png/detail/89-893195_39-1-april-2018-unknown-player-png.png",
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
