# Generated by Django 5.1.6 on 2025-02-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rmapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="number",
            field=models.IntegerField(unique=True),
        ),
    ]
